// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: bleconsole

#ifndef UI_CONSOLESCREEN_H
#define UI_CONSOLESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConsoleScreen
extern void ui_ConsoleScreen_screen_init(void);
extern void ui_ConsoleScreen_screen_destroy(void);
extern lv_obj_t * ui_ConsoleScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ConsoleScreen_Slider1;
extern lv_obj_t * ui_ConsoleScreen_Slider2;
extern lv_obj_t * ui_ConsoleScreen_Slider3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

