// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: bleconsole

#include "ui.h"

lv_obj_t * ui_ConsoleScreen = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider1 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider2 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider3 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider4 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider5 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider6 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider7 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider8 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider9 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider10 = NULL;
lv_obj_t * ui_ConsoleScreenNextButton = NULL;
lv_obj_t * ui_ConsoleScreen_Image1 = NULL;
// event funtions
void ui_event_ConsoleScreenNextButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VehicleScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_VehicleScreen_screen_init);
    }
}

// build funtions

void ui_ConsoleScreen_screen_init(void)
{
    ui_ConsoleScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ConsoleScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ConsoleScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -174);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Hello BLE console  (with image) !");

    ui_ConsoleScreen_Slider1 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider1, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider1, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider1, -300);
    lv_obj_set_y(ui_ConsoleScreen_Slider1, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider1,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider1,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider2 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider2, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider2, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider2, -250);
    lv_obj_set_y(ui_ConsoleScreen_Slider2, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider2,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider2,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider3 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider3, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider3, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider3, -200);
    lv_obj_set_y(ui_ConsoleScreen_Slider3, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider3,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider3,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider4 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider4, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider4, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider4, -150);
    lv_obj_set_y(ui_ConsoleScreen_Slider4, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider4,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider4,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider4, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider5 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider5, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider5, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider5, -100);
    lv_obj_set_y(ui_ConsoleScreen_Slider5, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider5,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider5,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider5, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider6 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider6, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider6, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider6, -50);
    lv_obj_set_y(ui_ConsoleScreen_Slider6, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider6,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider6,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider6, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider7 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider7, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider7, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider7, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider7, 0);
    lv_obj_set_y(ui_ConsoleScreen_Slider7, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider7,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider7,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider7, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider8 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider8, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider8) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider8, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider8, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider8, 50);
    lv_obj_set_y(ui_ConsoleScreen_Slider8, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider8,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider8,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider8, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider9 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider9, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider9) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider9, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider9, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider9, 100);
    lv_obj_set_y(ui_ConsoleScreen_Slider9, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider9,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider9,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider9, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreen_Slider10 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider10, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider10) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider10, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider10, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider10, 150);
    lv_obj_set_y(ui_ConsoleScreen_Slider10, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConsoleScreen_Slider10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_ConsoleScreen_Slider10,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_ConsoleScreen_Slider10,
                                                                                  lv_obj_get_style_pad_right(ui_ConsoleScreen_Slider10, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ConsoleScreenNextButton = lv_button_create(ui_ConsoleScreen);
    lv_obj_set_width(ui_ConsoleScreenNextButton, 100);
    lv_obj_set_height(ui_ConsoleScreenNextButton, 70);
    lv_obj_set_x(ui_ConsoleScreenNextButton, 289);
    lv_obj_set_y(ui_ConsoleScreenNextButton, 160);
    lv_obj_set_align(ui_ConsoleScreenNextButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConsoleScreenNextButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ConsoleScreenNextButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConsoleScreen_Image1 = lv_image_create(ui_ConsoleScreen);
    lv_obj_set_width(ui_ConsoleScreen_Image1, 130);
    lv_obj_set_height(ui_ConsoleScreen_Image1, 130);
    lv_obj_set_x(ui_ConsoleScreen_Image1, 248);
    lv_obj_set_y(ui_ConsoleScreen_Image1, -130);
    lv_obj_set_align(ui_ConsoleScreen_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConsoleScreen_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ConsoleScreen_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_ConsoleScreen_Image1, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_border_color(ui_ConsoleScreen_Image1, lv_color_hex(0xC22323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConsoleScreen_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConsoleScreen_Image1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ConsoleScreenNextButton, ui_event_ConsoleScreenNextButton, LV_EVENT_ALL, NULL);

}

void ui_ConsoleScreen_screen_destroy(void)
{
    if(ui_ConsoleScreen) lv_obj_del(ui_ConsoleScreen);

    // NULL screen variables
    ui_ConsoleScreen = NULL;
    ui_Label1 = NULL;
    ui_ConsoleScreen_Slider1 = NULL;
    ui_ConsoleScreen_Slider2 = NULL;
    ui_ConsoleScreen_Slider3 = NULL;
    ui_ConsoleScreen_Slider4 = NULL;
    ui_ConsoleScreen_Slider5 = NULL;
    ui_ConsoleScreen_Slider6 = NULL;
    ui_ConsoleScreen_Slider7 = NULL;
    ui_ConsoleScreen_Slider8 = NULL;
    ui_ConsoleScreen_Slider9 = NULL;
    ui_ConsoleScreen_Slider10 = NULL;
    ui_ConsoleScreenNextButton = NULL;
    ui_ConsoleScreen_Image1 = NULL;

}
