// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: bleconsole

#ifndef UI_CONSOLESCREEN_H
#define UI_CONSOLESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConsoleScreen
extern void ui_ConsoleScreen_screen_init(void);
extern void ui_ConsoleScreen_screen_destroy(void);
extern lv_obj_t * ui_ConsoleScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ConsoleScreen_Slider1;
extern lv_obj_t * ui_ConsoleScreen_Slider2;
extern lv_obj_t * ui_ConsoleScreen_Slider3;
extern lv_obj_t * ui_ConsoleScreen_Slider4;
extern lv_obj_t * ui_ConsoleScreen_Slider5;
extern lv_obj_t * ui_ConsoleScreen_Slider6;
extern lv_obj_t * ui_ConsoleScreen_Slider7;
extern lv_obj_t * ui_ConsoleScreen_Slider8;
extern lv_obj_t * ui_ConsoleScreen_Slider9;
extern lv_obj_t * ui_ConsoleScreen_Slider10;
extern void ui_event_ConsoleScreenNextButton(lv_event_t * e);
extern lv_obj_t * ui_ConsoleScreenNextButton;
extern lv_obj_t * ui_ConsoleScreen_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

