// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: bleconsole

#include "ui.h"

lv_obj_t * ui_ConsoleScreen = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider1 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider2 = NULL;
lv_obj_t * ui_ConsoleScreen_Slider3 = NULL;
// event funtions

// build funtions

void ui_ConsoleScreen_screen_init(void)
{
    ui_ConsoleScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConsoleScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ConsoleScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -174);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Hello BLE console !!!");

    ui_ConsoleScreen_Slider1 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider1, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider1, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider1, -300);
    lv_obj_set_y(ui_ConsoleScreen_Slider1, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConsoleScreen_Slider1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_ConsoleScreen_Slider2 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider2, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider2, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider2, -250);
    lv_obj_set_y(ui_ConsoleScreen_Slider2, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConsoleScreen_Slider2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_ConsoleScreen_Slider3 = lv_slider_create(ui_ConsoleScreen);
    lv_slider_set_value(ui_ConsoleScreen_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ConsoleScreen_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_ConsoleScreen_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ConsoleScreen_Slider3, 10);
    lv_obj_set_height(ui_ConsoleScreen_Slider3, 300);
    lv_obj_set_x(ui_ConsoleScreen_Slider3, -200);
    lv_obj_set_y(ui_ConsoleScreen_Slider3, 35);
    lv_obj_set_align(ui_ConsoleScreen_Slider3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConsoleScreen_Slider3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

}

void ui_ConsoleScreen_screen_destroy(void)
{
    if(ui_ConsoleScreen) lv_obj_del(ui_ConsoleScreen);

    // NULL screen variables
    ui_ConsoleScreen = NULL;
    ui_Label1 = NULL;
    ui_ConsoleScreen_Slider1 = NULL;
    ui_ConsoleScreen_Slider2 = NULL;
    ui_ConsoleScreen_Slider3 = NULL;

}
