// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: bleconsole

#include "ui.h"


// IMAGE DATA: assets/tgv.png
const char * ui_img_tgv_png = "S:assets/tgv.png";
