// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: bleconsole

#include "ui.h"

lv_obj_t * ui_VehicleScreen = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_VehicleScreenNextButton = NULL;
lv_obj_t * ui_VehicleScreen_Image = NULL;
lv_obj_t * ui_VehicleScreenPreviousButton = NULL;
// event funtions
void ui_event_VehicleScreenPreviousButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConsoleScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ConsoleScreen_screen_init);
    }
}

// build funtions

void ui_VehicleScreen_screen_init(void)
{
    ui_VehicleScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_VehicleScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_VehicleScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -174);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "VehicleScreen");

    ui_VehicleScreenNextButton = lv_button_create(ui_VehicleScreen);
    lv_obj_set_width(ui_VehicleScreenNextButton, 100);
    lv_obj_set_height(ui_VehicleScreenNextButton, 70);
    lv_obj_set_x(ui_VehicleScreenNextButton, 289);
    lv_obj_set_y(ui_VehicleScreenNextButton, 160);
    lv_obj_set_align(ui_VehicleScreenNextButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VehicleScreenNextButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_VehicleScreenNextButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VehicleScreen_Image = lv_image_create(ui_VehicleScreen);
    lv_obj_set_width(ui_VehicleScreen_Image, 130);
    lv_obj_set_height(ui_VehicleScreen_Image, 130);
    lv_obj_set_x(ui_VehicleScreen_Image, -273);
    lv_obj_set_y(ui_VehicleScreen_Image, -34);
    lv_obj_set_align(ui_VehicleScreen_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VehicleScreen_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_VehicleScreen_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_VehicleScreen_Image, lv_color_hex(0xC22323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VehicleScreen_Image, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VehicleScreen_Image, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VehicleScreenPreviousButton = lv_button_create(ui_VehicleScreen);
    lv_obj_set_width(ui_VehicleScreenPreviousButton, 100);
    lv_obj_set_height(ui_VehicleScreenPreviousButton, 70);
    lv_obj_set_x(ui_VehicleScreenPreviousButton, -300);
    lv_obj_set_y(ui_VehicleScreenPreviousButton, 160);
    lv_obj_set_align(ui_VehicleScreenPreviousButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VehicleScreenPreviousButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_VehicleScreenPreviousButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_VehicleScreenPreviousButton, ui_event_VehicleScreenPreviousButton, LV_EVENT_ALL, NULL);

}

void ui_VehicleScreen_screen_destroy(void)
{
    if(ui_VehicleScreen) lv_obj_del(ui_VehicleScreen);

    // NULL screen variables
    ui_VehicleScreen = NULL;
    ui_Label2 = NULL;
    ui_VehicleScreenNextButton = NULL;
    ui_VehicleScreen_Image = NULL;
    ui_VehicleScreenPreviousButton = NULL;

}
