// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: bleconsole

#ifndef UI_VEHICLESCREEN_H
#define UI_VEHICLESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_VehicleScreen
extern void ui_VehicleScreen_screen_init(void);
extern void ui_VehicleScreen_screen_destroy(void);
extern lv_obj_t * ui_VehicleScreen;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_VehicleScreenNextButton;
extern lv_obj_t * ui_VehicleScreen_Image;
extern void ui_event_VehicleScreenPreviousButton(lv_event_t * e);
extern lv_obj_t * ui_VehicleScreenPreviousButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

